### PR TITLE
Fixed error in energy integration with SPH and self-gravity

### PR DESCRIPTION
**Pull request by rbooth200**
This is the missing energy fix

### CODE REVIEW

**Comment by giovanni-rosotti** [comment]
This is fine. Just a quick question before merging: had we really not implemented the change already? Could it be that we have the similar commit in another branch we haven't merged yet?

**Comment by rbooth200** [comment]
I think there might be another fix in papertests, you could use that one instead if you prefer.

**Comment by giovanni-rosotti** [comment]
Do you mean 	008cc7f? Do I understand correctly that the extra 0.5 you added here is actually commented out in that commit, and is added directly only to the dudt of artificial viscosity? Because if yes, when we will merge everything we will get it two times...

**Comment by rbooth200** [comment]
Yep I've just checked and that appears to be correct. Lets just forget this and try to merge papertests asap?

**Comment by giovanni-rosotti** [comment]
ok agreed, let's do as you suggest. but i'll leave the pull request open until i've fixed papertests to remind me that i should action it quickly

**Comment by rbooth200** [comment]
I've tidied up the fix so it's like the one in paper tests and checked that the energy conservation is good in both cases.

**Pull request merged**
