### PR TITLE
Added missing paper tests

### PR DESCRIPTION
**Pull request by rbooth200**
I've added a couple of paper tests that were missing, we should probably include them.

### CODE REVIEW

**Comment by giovanni-rosotti** [comment]
So I've tried to run both python scripts and I can't (missing .dat files)... I guess you forgot to add the files in the commit?

**Comment by giovanni-rosotti** [comment]
dustywave says that the integration has failed (?)

**Comment by rbooth200** [comment]
Works fine for me. More info?

**Comment by giovanni-rosotti** [comment]
ZVODE--  At current T (=R1), MXSTEP (=I1) steps
       taken on this call before reaching TOUT
      In above message,  I1 =       500
      In above message,  R1 =  0.2917827165661D+01
/usr/local/lib/python2.7/site-packages/scipy/integrate/_ode.py:869:
UserWarning: zvode: Excess work done on this call. (Perhaps wrong MF.)
  'Unexpected istate=%s' % istate))
Traceback (most recent call last):
  File "dustywavetest.py", line 65, in <module>
    sol = DustyWave(sim, t)
  File "../dust_tests/dustywave_sol.py", line 142, in DustyWave
    return solver(time)[0]
  File "../dust_tests/dustywave_sol.py", line 102, in __call__
    sol = self._solve_system(list(time))
  File "../dust_tests/dustywave_sol.py", line 90, in _solve_system
    if not integ.successful(): raise RuntimeError('Integ failed')
RuntimeError: Integ failed

**Comment by rbooth200** [comment]
So that's the analytical solution script that is failing. Try increasing max_step in the integrator to 10k or something.

**Comment by giovanni-rosotti** [comment]
ok, in this way it works. i'll push the modification

**Comment by giovanni-rosotti** [comment]
done, for me this pull request is now fine. david, it is up to you to accept it now

**Pull request merged**
