### PR TITLE
Uninitialised and unused variables

### PR DESCRIPTION
**Pull request by dhubber**
Newer version of previous uninitialised variables pull request.  Cherry-picked from old branch onto newer up-to-date branch from master.  In summary includes : 
- Removal of unused variables
- Initialise any uninitialised variables to a sensible default value
- Casting some unsigned ints to ints in conditional statments (N.B. used C-style casts)
- Some code cleaning up, removal of old unused/out-of-date code
- A few small optimisations (by way of using some intermediate const variables)

Also given the code another sweep for newly introduced unused/uninitialised variables.  The only exceptions are the MultipleSourceIonisation.cpp and TreeRay.cpp files, which will be dealt with in a future pull request.  Hopefully this can be merged quickly before it goes out-of-date (again) with the master branch.

### CODE REVIEW

**Comment by giovanni-rosotti** [comment]
For me it's fine. The previous pull request has introduced a conflict which I am going to take care of (and I will also get rid of some commented code).

**Comment by giovanni-rosotti** [comment]
Rebase done - wait for my commit now

**Comment by rbooth200** [comment]
Assuming this passes travis, I'm happy for it to go.

**Comment by giovanni-rosotti** [comment]
Done. Richard, you should have the honour of merging the pull request as both David and I have been involved in the pull request.

**Comment by dhubber** [comment]
Ummmm, did you just close this branch without merging it Richard??

**Comment by rbooth200** [comment]
Looks like it...

**Pull request merged**
